# Generated by Django 5.2 on 2025-07-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatreport_reported_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatreport",
            name="reported_user",
        ),
        migrations.CreateModel(
            name="ModAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the moderation action",
                        null=True,
                        verbose_name="reason",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("HIDE_MESSAGE", "Hide Message"),
                            ("FLAG_USER", "Flag User"),
                            ("BLOCK_USER", "Block User"),
                        ],
                        help_text="The type of moderation action performed",
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "on_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mod_actions_on_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="on user",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mod_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
            ],
        ),
    ]
